### ISSUE TITLE
Something that should not be displayed is shown

### ISSUE THREAD

**Issue by Icenowy** [bobcao3/ALaunch#1]
The desktop file of Gtk+ 3.0 Demo is
[Desktop Entry]
Name=GTK+ Demo
Comment=GTK+ code examples and demonstrations
Exec=gtk3-demo
Icon=gtk3-demo
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;
NoDisplay=true

It has NoDisplay property.
However, it's shown in ALaunch
![2015-09-03 16-40-51](https://cloud.tithubusercontent.com/assets/1916518/9654070/a5bba0ba-525a-11e5-82d9-64bebab1f224.png)

**Comment by Icenowy** [comment]
![2015-09-03 16-40-51](https://cloud.githubusercontent.com/assets/1916518/9654079/bf5ffd2c-525a-11e5-877e-905aa187188f.png)

**Comment by Artoria2e5** [comment]
Next time, wrap <code>```INI</code> around desktop files.

**Comment by bobcao3** [comment]
Oh I see, this problem will be fixed when the vala version released. (The xdg is not well-supported)

**Comment by Icenowy** [comment]
I'd score 100/100 points for this delay reason. But valaizing is good.
- from Xperia Z3

---- Bob Cao编写 ----

Oh I see, this problem will be fixed when the vala version released. (The xdg is not well-supported)

---

**Comment by bobcao3** [comment]
Now it’s fixed and valalized
